pipeline {
    agent any 
    stages {
        stage('Pipeline to seed or update all pipelines') {
            steps {
                jobDsl  targets: ['FoldersCreation.groovy'].join('\n')
                jobDsl  targets: ['Front End/CoreWebVitals/*.groovy'].join('\n')
            }
        }
    }
}
