pipeline {
    agent any 
    stages {
        stage('Pipeline to seed or update all Smoke Tests pipelines') {
            steps {
                jobDsl  targets: ['OTT/OTT_all_test_cases.groovy'].join('\n')
            }
        }
    }
}
