pipeline {
    agent any 
    stages {
        stage('Pipeline to seed or update all pipelines') {
            steps {
                jobDsl  targets: ['MTOD Web/CoreWebVitals/FoldersCreation.groovy'].join('\n')
                jobDsl  targets: ['MTOD Web/CoreWebVitals/MTOD_Web_Core_Web_Vitals_Test_Cases.groovy'].join('\n')
            }
        }
    }
}
