pipeline {
    agent any 
    stages {
        stage('Pipeline to seed or update all Smoke Tests pipelines') {
            steps {
                jobDsl  targets: ['Front End/RegressionTests/*.groovy'].join('\n')
            }
        }
    }
}
